[package]
name = "harvest-daily"
version = "0.1.0"
authors = ["Arkadiusz Żmudzin <arek@moodup.team>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
